[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BorderGraph"
version = "0.1.0"
description = "Package to compute contours and neighbrhood graph considering the borders of the cells instead of the centroids. It allows more precise computation of the neighborhood graph."
readme = "README.md"
authors = [{name = "Jacopo Umberto Verga"}]
requires-python = ">=3.8"

dependencies = [
    "numpy",
    "scanpy",
    "squidpy",
    "anndata",
    "joblib",
    "scipy",
    "itertools",
    "pandas",
    "scikit-learn",
    "scikit-image"
]

[project.urls]
"Homepage" = "https://github.com/VergaJU/BorderGraph"
"Repository" = "https://github.com/VergaJU/BorderGraph"
